### PR TITLE
Handle loading directories by loading index.js.

### LINKED ISSUE #2: Use node-resolve to resolve files
[node-resolve](https://www.npmjs.com/package/resolve) is a widely used module to do node/npm module path resolution. This plugin should probably use it. It'd fix an issue for me, where `import foo from 'bar/foo';` fails to resolve to `node_modules/bar/foo/index.js` if that's the file node would have resolved given the same path to a `require` call.

### PR DESCRIPTION
**Pull request by eventualbuddha**
Closes #2.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Turns out I found some time to do this. Please let me know if I missed something! It looked like there might be a few cases not covered by the tests.

**Comment by Victorystick** [comment]
It looks really neat. That should be enough to ensure complete compatibility with Node for imports, right? 
@eventualbuddha  Do you think we should take the async route while we're at it?

**Comment by eventualbuddha** [comment]
> That should be enough to ensure complete compatibility with Node for imports, right?

I believe so.

> Do you think we should take the async route while we're at it?

Wouldn't hurt. I can modify it.

**Comment by eventualbuddha** [comment]
@Victorystick Updated. It seems to get me past the problem I was having trying to use the plugin (now I just have other problems, heh).

**Comment by eventualbuddha** [comment]
@Rich-Harris I'd like to merge this, but since I only have one project using this plugin right now I'm hesitant. Mind trying out this branch with something you're using it for? Once it's merged are you handling the npm releases?

**Comment by Victorystick** [comment]
:+1: Rich?

**Comment by Rich-Harris** [comment]
LGTM, thanks – have released it as 1.1.0 (and added you both as owners on npm!)

**Pull request merged**
