### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
@eventualbuddha

**Comment by Rich-Harris** [comment]
Thanks for the prod @TrySound :grinning:

**Comment by TrySound** [comment]
@Rich-Harris My pleasure. Don't forget to enable CI

**Comment by Rich-Harris** [comment]
It's enabled – one of the tests is [failing](https://github.com/rollup/rollup-plugin-npm/issues/12) though :frowning:

**Comment by TrySound** [comment]
@Rich-Harris Give me access please. I'll try to fix.

**Comment by Rich-Harris** [comment]
@TrySound awesome, thanks – have added you to the team, you should have access to this repo and probably various others in the Rollup organisation. Shout if it didn't work

**Comment by TrySound** [comment]
@Rich-Harris Thanks.

**Pull request merged**
