### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
@Rich-Harris Need to enable also travis

**Comment by TrySound** [comment]
On my windows everything is okay. And I will make some noise to fix appveyor.

**Comment by TrySound** [comment]
Do not merge yet please

**Comment by TrySound** [comment]
@Rich-Harris It was npm3 deduping :)

**Comment by eventualbuddha** [comment]
:+1:

**Comment by Rich-Harris** [comment]
> It was npm3 deduping :)

(╯°□°）╯︵ ┻━┻ 

Thanks! Have enabled Travis

**Pull request merged**
